server:
  port: 8090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/danielpradocussi/configserver.git
          searchPaths: /config-server-main/config-data
          default-label: "main"
        bootstrap: true
  security:
    user:
      name: root
      password: s3cr3t
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"

